import { useRef, useEffect, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { themeConfig } from '../theme/theme.config';
import { SplitTextComponent } from '../components/ui/SplitText';

gsap.registerPlugin(ScrollTrigger);

const showcaseItems = [
  {
    title: 'Cinematic Landscape',
    category: 'Environment',
    thumbnail: '🏔️',
  },
  {
    title: 'Product Visualization',
    category: 'Commercial',
    thumbnail: '📦',
  },
  {
    title: 'Architectural Concept',
    category: 'Architecture',
    thumbnail: '🏛️',
  },
  {
    title: 'Character Design',
    category: 'Character',
    thumbnail: '🎭',
  },
  {
    title: 'Sci-Fi Environment',
    category: 'Environment',
    thumbnail: '🚀',
  },
  {
    title: 'Fashion Editorial',
    category: 'Commercial',
    thumbnail: '👗',
  },
];

function ShowcaseCard({ item }: { item: typeof showcaseItems[0] }) {
  return (
    <div 
      className="group relative flex-shrink-0 w-80 md:w-96 showcase-card"
      style={{ scrollSnapAlign: 'start' }}
    >
      <div 
        className="relative aspect-[4/3] rounded-2xl overflow-hidden"
        style={{
          background: `linear-gradient(135deg, ${themeConfig.palette.surface} 0%, ${themeConfig.palette.surfaceAlt} 100%)`,
          border: `1px solid ${themeConfig.palette.surfaceAlt}40`,
        }}
      >
        <div className="absolute inset-0 flex items-center justify-center" style={{ color: themeConfig.palette.textMuted, fontSize: '4rem' }}>
          {item.thumbnail}
        </div>
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
        <div className="absolute bottom-0 left-0 right-0 p-6 transform translate-y-full group-hover:translate-y-0 transition-transform duration-500">
          <p className="text-xs font-medium mb-1" style={{ color: themeConfig.palette.primary, textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            {item.category}
          </p>
          <h3 className="text-lg font-semibold" style={{ color: themeConfig.palette.text, fontFamily: themeConfig.typography.display.fontFamily }}>
            {item.title}
          </h3>
        </div>
      </div>
    </div>
  );
}

export function Showcase() {
  const sectionRef = useRef<HTMLElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const [scrollProgress, setScrollProgress] = useState(0);

  useEffect(() => {
    const section = sectionRef.current;
    const scroller = scrollRef.current;
    if (!section || !scroller) return;

    const ctx = gsap.context(() => {
      // Pin the scroll container
      ScrollTrigger.create({
        trigger: section,
        start: 'top top',
        end: '+=300%',
        pin: true,
        pinSpacing: true,
        scrub: 1,
        onUpdate: (self) => {
          setScrollProgress(self.progress);
          if (scroller) {
            scroller.scrollLeft = self.progress * (scroller.scrollWidth - scroller.clientWidth);
          }
        },
      });

      // Animate cards on enter
      gsap.fromTo('.showcase-card', 
        { opacity: 0, y: 30, scale: 0.95 },
        { opacity: 1, y: 0, scale: 1, duration: 0.6, ease: 'expo.out', stagger: 0.08, scrollTrigger: { trigger: '.showcase-track', start: 'top 80%' }}
      );
    }, section);

    return () => ctx.revert();
  }, []);

  return (
    <section 
      ref={sectionRef}
      id="showcase"
      className="relative px-6"
      aria-labelledby="showcase-heading"
    >
      <div className="max-w-7xl mx-auto mb-12">
        <SplitTextComponent
          split="lines"
          stagger={0.1}
          duration={1}
          from={{ opacity: 0, y: 40 }}
          to={{ opacity: 1, y: 0 }}
        >
          <h2 
            id="showcase-heading"
            className="text-4xl md:text-5xl lg:text-6xl font-bold"
            style={{ 
              fontFamily: themeConfig.typography.display.fontFamily,
              background: `linear-gradient(135deg, ${themeConfig.palette.text} 0%, ${themeConfig.palette.secondary} 100%)`,
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            Created with DREAMFRAME
          </h2>
        </SplitTextComponent>
        <p className="mt-6 text-lg max-w-2xl" style={{ color: themeConfig.palette.textMuted, fontFamily: themeConfig.typography.body.fontFamily }}>
          Real scenes generated by our beta users. No post-processing — straight from the engine.
        </p>
      </div>

      <div 
        ref={scrollRef}
        className="overflow-x-auto scrollbar-hide pb-8 -mx-6 px-6"
        style={{ scrollSnapType: 'x mandatory' }}
      >
        <div className="showcase-track flex gap-6" style={{ scrollSnapType: 'x mandatory' }}>
          {showcaseItems.map((item) => (
            <ShowcaseCard key={item.title} item={item} />
          ))}
        </div>
      </div>

      {/* Scroll progress indicator */}
      <div className="fixed bottom-8 left-1/2 -translate-x-1/2 w-64 h-1 pointer-events-none" style={{ backgroundColor: themeConfig.palette.surfaceAlt, borderRadius: '9999px' }}>
        <div 
          className="h-full rounded-full transition-transform duration-100"
          style={{ 
            background: `linear-gradient(90deg, ${themeConfig.palette.primary}, ${themeConfig.palette.accent})`,
            transformOrigin: 'left center',
            transform: `scaleX(${scrollProgress})`,
          }}
        />
      </div>

      {/* Scroll hint */}
      <div className="text-center mt-8" style={{ color: themeConfig.palette.textMuted }}>
        <p className="text-sm mb-2">Scroll horizontally to explore →</p>
        <div className="flex justify-center gap-2">
          {[...Array(6)].map((_, i) => (
            <div 
              key={i}
              className="w-2 h-2 rounded-full transition-all duration-300"
              style={{ 
                backgroundColor: i / 5 <= scrollProgress ? themeConfig.palette.primary : themeConfig.palette.surfaceAlt,
                transform: `scale(${i / 5 <= scrollProgress ? 1.2 : 1})`,
              }}
            />
          ))}
        </div>
      </div>
    </section>
  );
}